### ISSUE TITLE
!python qsr_ctc_wer.py : name 'char_y_val' is not defined

### ISSUE THREAD

**Issue by rkuo2000** [huckiyang/speech_quantum_dl#4]
File "qsr_ctc_wer.py", line 71, in <module>
    print("-- Validation Size: ", np.array(char_y_val).shape, np.array(new_x_val).shape, np.array(new_q_val).shape)
NameError: name 'char_y_val' is not defined

So I remove #68 else,
Then 

line 47, 48 & 53, 54 : labels_10 not defined,

After I add, 
labels_10 = ['left', 'go', 'yes', 'down', 'up', 'on', 'right', 'no', 'off', 'stop',]

I can finish the run, but I got WER=100% ?

It seems #69 input is in wrong order ? 
So I changed it to

char_y_tr, char_y_val, new_x_tr, new_x_val, new_q_tr, new_q_val = get_asr_data(y_train, y_valid, x_train, x_valid, q_train, q_valid)

But I still got WER=100%

**Comment by rkuo2000** [comment]
line 47 & 53 : labels_10 not defined, should it be changed to labels ?

**Comment by huckiyang** [comment]
Hi @rkuo2000 thank you for your interest in CTC word recognition again. 

I think it is still the revised augment issue, and I have updated the augments. See the updated [qsr_ctc_wer.py](https://github.com/huckiyang/speech_quantum_dl/blob/main/qsr_ctc_wer.py#L17). You can directly go by `git pull` for the updated version. 

for the ctc labels please use (which echo to the `asr_q_test_demo.npy ` ... and so)

```python
labels_ctc = [
    'bird', 'down', 'five', 'four', 'left', 'nine', 'stop', 'tree', 'zero',]
```

and modify lines 48 and 54 from `labels` to `labels_ctc` to generate the transcription for ctc loss.

```python
char_y_val.append(labels_ctc[np.argmax(y)])
```

and it should work with around ~10% WER. Thanks.

**Comment by rkuo2000** [comment]
if labels_ctc[np.argmax(y)] in labels:     <-- labels is missing

after adding labeles = labels = [ 'left', 'go', 'yes', 'down', 'up', 'on', 'right', 'no', 'off', 'stop',]
then   np.argmax(y) has Error : out of range index of labels_ctc  
since labels_ctc has only 9 items, but labels has 10 (which y_valid, y_train are all 10 items)

but if I changed them to 

        if labels[np.argmax(y)] in labels_ctc:
            char_y_tr.append(labels[np.argmax(y)])

I still got WER=100%

**Comment by huckiyang** [comment]
Hi @rkuo2000 , I found that the issue caused by the limited provided data.
I just rewrite the file and upload 5 times more features for the CTC training. 
Please refer to the updated [section](https://github.com/huckiyang/speech_quantum_dl/blob/main/README.md#33-ctc-model-for-automatic-speech-recognition) for the feature unzip. 

I have also updated the pre-trained [weight](https://github.com/huckiyang/speech_quantum_dl/blob/main/checkpoints/asr_ctc_demo.hdf5) for the ctc model. 

```python
Epoch 32/50
107/107 [==============================] - 5s 49ms/step - loss: 0.1191 - val_loss: 0.7115
Epoch 33/50
107/107 [==============================] - 5s 49ms/step - loss: 0.1547 - val_loss: 0.6701
=== WER: 9.895833333333334  %  
```

**Comment by rkuo2000** [comment]
fid = open(os_fspath(file), "rb")
FileNotFoundError: [Errno 2] No such file or directory: 'data_quantum/asr_set/asr_x_tr.npy''

**Comment by huckiyang** [comment]
> ```
> fid = open(os_fspath(file), "rb")
> ```
> 
> 
> FileNotFoundError: [Errno 2] No such file or directory: 'data_quantum/asr_set/asr_x_tr.npy''

Please read the update read me carefully.
You did not run unzip.sh. https://github.com/huckiyang/speech_quantum_dl#33-ctc-model-for-automatic-speech-recognition

**Comment by rkuo2000** [comment]
Is there something wrong while bash unzip.sh?

Archive:  tmp1.zip
warning [tmp1.zip]:  zipfile claims to be last disk of a multi-part archive;
  attempting to process anyway, assuming all parts have been concatenated
  together in order.  Expect "errors" and warnings...true multi-part support
  doesn't exist yet (coming soon).
warning [tmp1.zip]:  292552704 extra bytes at beginning or within zipfile
  (attempting to process anyway)
file #1:  bad zipfile offset (local header sig):  292552708
  (attempting to re-compensate)
  inflating: asr_q_tr.npy            
Archive:  tmp2.zip
warning [tmp2.zip]:  zipfile claims to be last disk of a multi-part archive;
  attempting to process anyway, assuming all parts have been concatenated
  together in order.  Expect "errors" and warnings...true multi-part support
  doesn't exist yet (coming soon).
warning [tmp2.zip]:  97517568 extra bytes at beginning or within zipfile
  (attempting to process anyway)
file #1:  bad zipfile offset (local header sig):  97517572
  (attempting to re-compensate)
  inflating: asr_x_tr.npy            
Archive:  asr_q_val.zip
  inflating: asr_q_val.npy     

the file data_quantum/asr_set/asr_x_tr.npy is there, but !python qsr_ctc_wer.py still gives error:

  File "qsr_ctc_wer.py", line 65, in <module>
    new_x_tr = np.load(SAVE_PATH + "asr_x_tr.npy")
  File "/opt/conda/lib/python3.7/site-packages/numpy/lib/npyio.py", line 428, in load
    fid = open(os_fspath(file), "rb")
FileNotFoundError: [Errno 2] No such file or directory: 'data_quantum/asr_set/asr_x_tr.npy'

**Comment by huckiyang** [comment]
@rkuo2000 GitHub has a size limit of 100 MB per file. That’s why we have to use separated zip files here. 

The bash information looks ok to me; there were just warnings without actual error messages. 

Can you check the file size in your disk by 
`ls -l` ? For `x_tr`, it should be above 200 MB. 

```python
412352768 Dec 31 19:41 asr_q_tr.npy
103118528 Dec 31 19:41 asr_q_val.npy
206176448 Dec 31 19:41 asr_x_tr.npy
51559328 Dec 31 19:41 asr_x_val.npy
54546 Dec 31 19:41 char_y_tr.json
13642 Dec 31 19:41 char_y_val.json
```

or may you share where is the root to double-check the file path?

**Comment by rkuo2000** [comment]
Probably Kaggle did not reset well to have a clean restart.
I have rerun it, and it runs OK now.
my Kaggle [QCNN-ASR](https://www.kaggle.com/rkuo2000/qcnn-asr)  for reference.

**Comment by huckiyang** [comment]
Good to know it works. Thanks!
